stages:
  load_data:
    cmd: python src/load_data.py
    outs:
    - data/features_iris.csv
  split_data:
    cmd: python src/split_dataset.py --test_size 0.2
    deps:
    - data/features_iris.csv
    outs:
    - data/test.csv
    - data/train.csv
  train_model:
    cmd: python src/train.py
    deps:
    - data/train.csv
    - src/train.py
    outs:
    - metrics.csv
    - models/model.pkl
